name: radar-tools
channels:
- conda-forge
- defaults
dependencies:
- python=2.7
- arm_pyart
- basemap
- basemap-data-hires
- matplotlib
- jupyter
- pandas
- xarray
- numpy
- cython
- wget
- lxml
- pyproj
- pip:
  - skewt
  - git+git://github.com/CSU-Radarmet/CSU_RadarTools.git
