name: radar
channels:
- conda-forge
- defaults
dependencies:
- python=2.7
- arm_pyart
- basemap
- basemap-data-hires
- matplotlib
- jupyter
- pandas
- numpy
- cython
- wget
- pip:
  - skewt
  - git+git://github.com/CSU-Radarmet/CSU_RadarTools.git
